[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/generate-saml-assertion"
  to = "/.netlify/functions/generate-saml-assertion"
  status = 200
